version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  celery:
    build:
      context: .
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    restart: on-failure
    depends_on: 
      - rabbitmq
    command: >
      sh -c "celery -A settings.celery.celery_config worker -l info -P "

  flower:
    image: mher/flower:0.9.7
    restart: on-failure
    depends_on: 
      - rabbitmq
      - celery
    ports:
      - "5555:5555"
    command: ["flower", "--broker=pyamqp://guest:guest@rabbitmq:5672//", "--port=5555"]

volumes:
  rabbitmq:
