version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "${APP_CONFIG__POSTGRES_DB:-db}"
      POSTGRES_USER: "${APP_CONFIG__POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${APP_CONFIG__POSTGRES_PASSWORD:-root}"
    env_file:
      - src/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  pg_data: