version: "3.9"
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "${APP_CONFIG__POSTGRES_DB:-db}"
      POSTGRES_USER: "${APP_CONFIG__POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${APP_CONFIG__POSTGRES_PASSWORD:-root}"
    env_file:
      - src/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  rabbitmq:
    image: rabbitmq:4.0.4-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:-guest}"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
  pg_data: